services:
  web:
    build: .
    restart: always
    ports:
      - "8080:80"
    environment:
      DB_HOST: chateadb.cb0c8ua4uka7.ap-southeast-2.rds.amazonaws.com
      DB_USER: admin
      DB_PASSWORD: Chatea1234!
      DB_NAME: asg_3
    volumes:
      - .:/var/www/html
